spring:
  application:
    name: ReceiptHandler

  datasource:
    url: jdbc:postgresql://localhost:5432/receipt_scanner_dev
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  endpoints:
    web:
      exposure:
        include: health

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}


jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 9000000
  refresh-expiration: 604800000

